name: Swift

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install linting tools
        run: brew install swiftlint xcpretty

      - name: Lint
        run: swiftlint --strict

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build iOS app
        run: |
          xcodebuild \
            -project Phonepedia.xcodeproj \
            -scheme "Phonepedia (2023)" \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            build | xcpretty && exit ${PIPESTATUS[0]}

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build macOS app
        run: |
          xcodebuild \
            -project Phonepedia.xcodeproj \
            -scheme "Phonepedia (2023)" \
            -configuration Debug \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            build | xcpretty && exit ${PIPESTATUS[0]}
